name: YTUSocial Otomatik Deploy

on:
  push:
    branches:
      - main  # Eğer GitHub'daki ana dalının adı master ise burayı master yap

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sunucuya Bağlan ve Güncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Doğru klasöre git
            cd /root/ytusocial_project/ytusocial 
            
            # 2. GitHub'daki en güncel kodların listesini al (henüz indirme)
            git fetch --all
            
            # 3. ZORLA GÜNCELLE: Sunucudaki app.py vb. manuel değişiklikleri ez, GitHub'ı birebir kopyala
            git reset --hard origin/main
            
            # 4. Flask uygulamasını (servisini) yeniden başlat ki yeni kodlar canlıda devreye girsin
            systemctl restart ytusocial